name: BuildPush

on:
  push:
    branches: [ main ]

jobs:
  versionning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.genver.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Generate Version
      id: genver
      run: |
        VERSION=$(docker run --rm -v $(pwd):/repo codacy/git-version /bin/git-version --folder=/repo --release-branch=main --dev-branch=dev) 
        echo "::set-output name=version::$VERSION"
        echo $VERSION
 
  build:
    runs-on: ubuntu-latest
    needs: versionning
    env:
      VERSION: ${{ needs.versionning.outputs.version }}
    strategy:
      matrix:
        Configuration: ['Release', 'Debug']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        submodules: true

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Build the package
      run: dotnet build Api/csharp/ArmoniK.Api/ArmoniK.Api.csproj -c ${{ matrix.Configuration }}

    - name: Pack the package
      run: |
        dotnet pack Api/csharp/ArmoniK.Api/ArmoniK.Api.csproj -c ${{ matrix.Configuration }} -o /tmp/packages -p:PackageVersion=$VERSION
        ls /tmp/packages

  tag:
    runs-on: ubuntu-latest
    needs: build
    env:
      VERSION: ${{ needs.versionning.outputs.version }}
    steps:
    - name: tag
      run: |
        git tag $VERSION
        git push origin $VERSION
